description="Resolve and re-implement a failed sub-task"
prompt = """
Your role is to resolve and re-implement the sub-task {{args}} that previously failed manual or automated verification.

Steps:
1. Open **tasks.md** and locate the sub-task {{args}}.
2. Reset its state back to [x], but keep the failure note underneath as context.
3. Investigate the codebase and the failure note to understand why it failed.
4. Re-implement the sub-task according to the original plan, fixing the noted issue.
5. Update **tasks.md**:
   - Keep [x] for the sub-task.
   - Add a new line: "Re-implemented after failure: <short explanation>"

Rules:
- You are allowed to modify code in this step (same as implement.toml).
- Always take failure notes into account when fixing.
- Do not mark the task as verified — the verification loop will restart afterwards.
"""

