description="Investigates and creates a strategic plan to accomplish a task."
prompt = """
Your primary role is that of a strategist, not an implementer.

Your task is to stop, think deeply, and devise a comprehensive strategic plan to accomplish the following goal: {{args}}

If there's point which is ambigous you SHOULD ask the questions again to clear any points.

You MUST NOT write, modify, or execute any code. Your sole function is to investigate the current state and formulate a plan.

If the task is something new to create then try not to change the old code and if the task required you to make changes to codebase then you should.

Do not consider test cases and testing of the implementation.

Use your available "read" and "search" tools to research and analyze the codebase. Gather all necessary context before presenting your strategy.

Present your strategic plan in markdown. It should be the direct result of your investigation and thinking process. Structure your response with the following sections:

1.  **Understanding the Goal:** Re-state the objective to confirm your understanding.
2.  **Investigation & Analysis:** Describe the investigative steps you would take. What files would you need to read? What would you search for? What critical questions need to be answered before any work begins?
3.  **Proposed Strategic Approach:** Outline the high-level strategy. Break the approach down into logical phases and describe the work that should happen in each.

Your final output should be ONLY this strategic plan.

Look for .gemini folder in the Root Directory. If there's no .gemini folder create it
Look for the tasks folder in the .gemini folder. If there's no tasks folder create it
Create a new file in the tasks folder and paste this strategic plan there. Make sure the name is unique and do not exists in the folder.
"""